### ISSUE TITLE
if you don't specify the parameter name in the cpp, the linter won't cry about the unused parameter and we save on some boilerplate

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_control#115]
if you don't specify the parameter name in the cpp, the linter won't cry about the unused parameter and we save on some boilerplate

```suggestion
  hardware_interface_ret_t configure(const ComponentInfo & /* actuator_info */)
  {
    return hardware_interface::HW_RET_OK;
  }
```

The currently used alternative is
```
  hardware_interface_ret_t configure(const ComponentInfo & actuator_info)
  {
    (void) actuator_info;
    return hardware_interface::HW_RET_OK;
  }
```
Functionally they are equivalent, silencing the linter on unused argument.

_Originally posted by @bmagyar in https://github.com/ros-controls/ros2_control/pull/101_

**Comment by bmagyar** [comment]
@Karsten1987 @jordan-palacios @v-lopez @destogl please weigh in on this here.

My vote is with commenting out the argument name, I think it is a much cleaner way of denoting not wanting to use an argument. It is also one line less, overall reducing litter in the code.

**Comment by v-lopez** [comment]
Comment out or remove altogether from the .cpp and leave on the hpp only.

**Comment by Karsten1987** [comment]
I actually don't remember why we do this all over the place within the ros2 stack. I thought to remember that one of the linters (cppcheck, cpplint, uncrustify) would complain about it. If that's not the case any longer, I am okay with having the argument commented out.

**Comment by jordan-palacios** [comment]
Agreed with the previous responses, commenting out the argument is the way.

**Comment by destogl** [comment]
So it seams we are rather going for removing the arguments. see [comment](https://github.com/ros-controls/ros2_controllers/pull/125#discussion_r541755377)

**Comment by bmagyar** [comment]
Done!!
