### ISSUE TITLE
Proposed interface with MoveIt2 (high level)

### ISSUE THREAD

**Issue by AndyZe** [ros-controls/ros2_control#116]
As discussed in the Work Group meeting, here's the proposed interface between MoveIt2 and ros2_control.

First, the old ROS1 design that used an action interface to communicate with a trajectory controller. In the case of reactive control, a ROS topic was used to communicate with e.g. a JointGroupPositionController.

![ros1_moveit_control_interface](https://user-images.githubusercontent.com/11284393/86277271-0d42df00-bb9c-11ea-8064-a5aecb5ef188.png)

The new design is vague still, but we want to run the planning node as a component of a composable node. Ideally, ros2_control would be another component, and the user application would be a 3rd component. This should allow zero-copy data sharing and probably some other optimizations I'm not aware of. Basically, it would make multi-threading very easy and performant.

New design:
![ros2_moveit_control_interface](https://user-images.githubusercontent.com/11284393/86277563-86dacd00-bb9c-11ea-8202-2c73c98482f0.png)

In this issue, I just seek reassurance that your planned design is compatible with this proposal.

**Comment by destogl** [comment]
duplicate to the #330 therefore closing
