### ISSUE TITLE
[Diagnostics] - A non active controller should not be reported as error

### ISSUE THREAD

**Issue by firesurfer** [ros-controls/ros2_control#1183]
**Describe the bug**

Currently controllers that are loaded but are deactivated are reported as errors via ROS diagnostics. 
![grafik](https://github.com/ros-controls/ros2_control/assets/8481806/83b756b3-c8ad-4173-9d04-a7ab31b3a123)

I think this should be a warning. In my system for example I regularly switch controllers (e.g. from a compliant controller to the jtc and back). The other controller being inactive is desired behavior in that case and should not be reported as an error.

**To Reproduce**

Load a controller and deactivate it

**Expected behavior**

Report nothing or just a warning via ROS diagnostics

**Environment (please complete the following information):**
 - OS:  Ubuntu 22.04
 - Version iron

**Comment by firesurfer** [comment]
@saikishor I created a PR which just makes the switch from Error to Warn. Not sure if there is any other error information to report  about controller (such as ros2 control could not active the controller)

**Comment by christophfroehlich** [comment]
Is this fixed with #1184?

**Comment by saikishor** [comment]
@christophfroehlich yes it should be fixed. Now it won't report it as an error
