### ISSUE TITLE
ros2_controller CI is broken for Iron

### ISSUE THREAD

**Issue by christophfroehlich** [ros-controls/ros2_control#1285]
See the following jobs: 

- https://github.com/ros-controls/ros2_controllers/actions/runs/7436961863/job/20403754972
- https://github.com/ros-controls/ros2_controllers/actions/runs/7436961900/job/20234036118

For humble or rolling the same tests work. Semi-binary jobs works also with iron.
It seems that test_components are not shipped with the binaries; they are in the BUILD_TESTING branch. 

https://github.com/ros-controls/ros2_control/blob/71506d5f12e1e8529be4951ccf45f7144969f841/hardware_interface/CMakeLists.txt#L82-L96

@bmagyar Is it possible that iron packages are built with BUILD_TESTING false, but others with true?

**Comment by saikishor** [comment]
Thanks for bringing it up!

At PAL, we also have a similar issue with the `test_components`, when built on our internal CI. It doesn't build this library, hence for all the internally developed controllers, we couldn't add similar tests. Atleast, we build our debians with the `BUILD_TESTING` flag to `false`.

**Comment by destogl** [comment]
It might be that because `ros2_control_test_assets` is only dependent on the tests, it is not shipped or appropriately added to the hierarchy. I believe that we use it only in the testing part as a dependency.

**Comment by christophfroehlich** [comment]
Should we change it and export it for `BUILD_TESTING` false also? or can we change the flag on the build farm to match the other distros?

**Comment by saikishor** [comment]
I think it is better to place it outside the tests and export it so that the other controller tests can use it. All CIs will more or less have the similar issue as it is not normal to generate your debians with `BUILD_TESTING` flag set to `true`.

**Comment by christophfroehlich** [comment]
conclusion of today's meeting: Lets make `hardware_interface_test` package, which installs the test components and move the tests from `hardware_interface` using those components also there to break the circular dependency.
