### ISSUE TITLE
Purpose of controller_parameter_server?

### ISSUE THREAD

**Issue by samiamlabs** [ros-controls/ros2_control#13]
Hi,

Is there some specific reason parameters are loaded using the custom ```controller_parameter_server``` package instead of how it is done in [nav2_bringup](https://github.com/ros-planning/navigation2/tree/a396dc5e575b07114545b350915739bf8e705cb7/nav2_bringup) for example.

Did that method of loading parameters not exist when you started working on this?

**Comment by Karsten1987** [comment]
That's exactly the reason for it. Parameters weren't as evolved as they are right now. I'll hope to have some spare time to work on this in the future. But I am also happy to review a PR for this :)
