### ISSUE TITLE
Update component parsing to cover changes to min-max

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_control#132]
Update the example URDFs in the component parser tests [here](https://github.com/ros-controls/ros2_control/blob/master/hardware_interface/test/test_component_parser.cpp) and apply the necessary changes on the parser implementation to support them.

Related to
https://github.com/ros-controls/roadmap/issues/23
https://github.com/ros-controls/roadmap/pull/25

**Comment by AndyZe** [comment]
Working on this

**Comment by AndyZe** [comment]
@bmagyar @destogl Does component_info.cpp need to be updated as well, or is it correct now? Here's the data structure there:

```
/**
 * \brief This structure stores information about components defined for a specific hardware
 * in robot's URDF.
 */
struct ComponentInfo
{
  /**
   * \brief name of the component.
   */
  std::string name;
  /**
   * \brief type of the component: sensor or actuator.
   */
  std::string type;
  /**
   * \brief component's class, which will be dynamically loaded.
   */
  std::string class_type;
  /**
   * \brief name of the command interfaces that can be set, e.g. "position", "velocity", etc.
   * Used by joints.
   */
  std::vector<std::string> command_interfaces;
  /**
   * \brief name of the state interfaces that can be read, e.g. "position", "velocity", etc.
   * Used by Joints and Sensors.
   */
  std::vector<std::string> state_interfaces;
  /**
   * \brief (optional) key-value pairs of components parameters.
   */
  std::unordered_map<std::string, std::string> parameters;
};
```

**Comment by destogl** [comment]
I reopen this since the issue is not settled completely (see [comment](https://github.com/ros-controls/ros2_control/pull/167#pullrequestreview-512395931))

**Comment by Karsten1987** [comment]
I am btw strongly against CamelCase [here](https://github.com/ros-controls/ros2_control/blob/891f524ee4a9f9cc7c7ddccfb078db8b23435c41/hardware_interface/src/component_parser.cpp#L35-L36) and would vote for `snake_case`. I don't see any help in searching for "commandInterfaceType". First off, I believe the tag name is too long, but then the parser should at least allow for variants of this such as `commandinterfacetype`, `CommandInterfaceType`, `commandInterfacetype`, etc.

**Comment by destogl** [comment]
> I am btw strongly against CamelCase [here](https://github.com/ros-controls/ros2_control/blob/891f524ee4a9f9cc7c7ddccfb078db8b23435c41/hardware_interface/src/component_parser.cpp#L35-L36) and would vote for `snake_case`.

I agree. We should update the example descriptions in the roadmap repo and then also the parser, as soon as we merge ros-controls/roadmap#27
