### ISSUE TITLE
Add `controller_manager_node` to `controller_manager` package

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_control#142]
Goal for  `loop()`:

```
read
update_controllers
write
```

as per demo repo #37

Make sure to have `ControllerManagerNode` as a separate class and a separate one with executor + main functions. The `ControllerManagerNode`  class should allow users to compose ros2_control with other nodes.

**Comment by bmagyar** [comment]
#216  and #236 contain an alternative implementation of this

**Comment by destogl** [comment]
This is done in #236
