### ISSUE TITLE
Document `calculate_dynamics` of mock hardware

### ISSUE THREAD

**Issue by christophfroehlich** [ros-controls/ros2_control#1490]
Document `calculate_dynamics` of mock hardware [here](https://control.ros.org/master/doc/ros2_control/hardware_interface/doc/mock_components_userdoc.html).

**Comment by emp0012** [comment]
Is the parameter "calculate_dynamics" required when we use a velocity controller with mock components?

**Comment by christophfroehlich** [comment]
I think this is more of a legacy. The feature was added later, and set to false to avoid breaking behaviours. But we could discuss if it should be default true, I agree with you on that.

**Comment by christophfroehlich** [comment]
Fixed with https://github.com/ros-controls/ros2_control/pull/1498
