### ISSUE TITLE
Unify return_type nomenclature in hardware_interface and controller_interface

### ISSUE THREAD

**Issue by v-lopez** [ros-controls/ros2_control#151]
I propose the name change to keep the same nomenclature as for `hardware_interfaces`. What do you think?

```suggestion
  return controller_interface::return_type::OK;
```

_Originally posted by @destogl in https://github.com/ros-controls/ros2_control/pull/139#discussion_r489326777_

hardware_interface uses `OK` and controller_interface uses `SUCCESS`

**Comment by bmagyar** [comment]
I agree and I think we should pick the shorter one, I vote for `OK`.

**Comment by destogl** [comment]
I vote also foe OK. It is a bit broader term, but still with the clear meaning.

**Comment by Karsten1987** [comment]
OK sounds good to me, too.

**Comment by v-lopez** [comment]
All right, I'll do after https://github.com/ros-controls/ros2_control/pull/139 is merged to avoid conflicts

**Comment by destogl** [comment]
So we go with `OK`. Rename `return_type::SUCCESS` everywhere to `return_type:OK`.  But keep `SUCCESS` where it is defined and make its value equal to `OK`. Mark `SUCCESS` is deprecated.
