### ISSUE TITLE
Multi-Robot Configuration Issue

### ISSUE THREAD

**Issue by anath93** [ros-controls/ros2_control#1552]
Everything works for individual robot. Approach is to use namespaces instead of ${prefix} in urdf.

Issue:

Unable to load controller using spawner (following this [tutorial](https://control.ros.org/master/doc/ros2_control/controller_manager/doc/userdoc.html#spawner).
Currently on Humble Binaries.
Complaining about 'type' parameter but that is configured in the yaml file.

![image](https://github.com/ros-controls/ros2_control_demos/assets/130472005/0e77b7f5-1848-4161-bccb-abf7c912a36d)
![image](https://github.com/ros-controls/ros2_control_demos/assets/130472005/3af45631-b8a0-4881-a8a1-a0707718bb8c)
![image](https://github.com/ros-controls/ros2_control_demos/assets/130472005/506f74e8-0711-4e2e-9456-dfd06037232d)

**Comment by anath93** [comment]
@christophfroehlich leading '/' gets appended in name spacing controller manager which is not tf_prefix standard in ROS side.

![image](https://github.com/ros-controls/ros2_control/assets/130472005/6a4f0236-10c3-4d13-9c21-41514c42438f)
 
![image](https://github.com/ros-controls/ros2_control/assets/130472005/c748e665-e02b-4b8a-b0d6-2f9f6dd488b9)

**Comment by christophfroehlich** [comment]
The PR is not approved yet, how could I know a release date?

**Comment by anath93** [comment]
@christophfroehlich there is no need of this PR, I will write solution to this where this PR is created for visibility of all. Closing this for now.
