### ISSUE TITLE
Benefits of ROS2 Control

### ISSUE THREAD

**Issue by rcarnemollaBE** [ros-controls/ros2_control#1590]
Hello, non-technical question here. I am considering using ROS2 control, particularly the differential drive controller, for a project and was curious, what are the benefits of using ROS2 control over writing a controller from scratch? Is it easy to interface with and modify the ROS2 controllers in this library? Any information would be appreciated!

**Comment by christophfroehlich** [comment]
Closing in favor of https://robotics.stackexchange.com/questions/111964/benefits-of-ros2-control
