### ISSUE TITLE
Remove ControllerLoaderInterface

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_control#160]
https://github.com/ros-controls/ros2_control/pull/139#discussion_r489310568

**Comment by mateus-amarante** [comment]
I would like to get deeper into ros2, so I propose to start solving good first issues. May I get this one?

I only have some questions about it:
* Should `ControllerLoaderPluginlib` exist (as a`ControllerLoader`) or can it be  `pluginlib::ClassLoader<controller_interface::ControllerInterface>` directly?

* Does the list of loaders inside the `ControllerManager` make sense? Can I remove it too?

**Comment by Karsten1987** [comment]
#175 is a first start to do that. It needs a bit more love though. If you don't mind, please feel free to take over that PR and either open a PR against that branch or cherry-pick the existing commits onto your own branch and open a new PR from your branch.

Happy to hand this one over :)

**Comment by mateus-amarante** [comment]
I didn't see #175. You have already done most of the update :)

I'll finish it.
