### ISSUE TITLE
Unable to fetch binaries for Iron distro ARM64

### ISSUE THREAD

**Issue by anath93** [ros-controls/ros2_control#1616]
**Expected behavior**
ros2 package page show that these packages are released
https://index.ros.org/r/ros2_controllers/github-ros-controls-ros2_controllers/#iron

**Screenshots**
![image](https://github.com/user-attachments/assets/f4e3d2e0-a347-4dff-9023-f9e4c09c8e45)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version Iron

It works for Humble.

**Comment by christophfroehlich** [comment]
which ubuntu are you using?

**Comment by anath93** [comment]
22.04

**Comment by anath93** [comment]
@christophfroehlich, would be better to build locally for now or simple fix ?

**Comment by christophfroehlich** [comment]
have you set the apt-list properly and run apt-get update afterwards?

**Comment by anath93** [comment]
Yes ! All the other packages are good except ros2_control and ros2_controllers.

**Comment by anath93** [comment]
Its recently upstream issue on recent sync of iron for ARM64 platform.

**Comment by christophfroehlich** [comment]
Thanks for reporting.
https://robotics.stackexchange.com/questions/112249/ros2-iron-arm64-packages-vanished
https://discourse.ros.org/t/ros2-iron-arm64-packages-vanished/38652/2

Any idea what happened @bmagyar ?

**Comment by christophfroehlich** [comment]
However, the last build [was successful](https://build.ros2.org/view/Ibin_ujv8_uJv8/job/Ibin_ujv8_uJv8__controller_interface__ubuntu_jammy_arm64__binary/), hopefully this solves itself with the next iron sync. @anath93 you can try the [testing repo](https://docs.ros.org/en/iron/Installation/Testing.html) in the meantime.

**Comment by anath93** [comment]
The sync took place and packages back to there current release. 

https://discourse.ros.org/t/new-packages-for-iron-irwini-2024-07-17/38674
