### ISSUE TITLE
Implement ResourceManager based on Components

### ISSUE THREAD

**Issue by Karsten1987** [ros-controls/ros2_control#164]
With the newly introduced components, the requirements for the resource manager are as follows:

* Remodel Hardware Components
  * Remove existing "joint" and "sensor" components
  * Move hardware resources into components namespace and use as such
  * Update component parser to reflect changes
* Remodel Component Interfaces
  * Introduce handles for command and state interfaces to hardware components
  * Update hardware classes to instantiate these handles given a list of interface strings
* Allocate initial memory for each of these components - these components are fix on runtime
* Provide Resource Loaning mechanism:
  * Handles to components can be uniquely loaned/assigned to controllers
  * Components are automatically released when controller is shutdown/unloaded
* Controller Manager iterates over all components for read/write
* Change Controller Interface to access "SingleValueComponent" through resource manager

Changes will be made according to the design draft here: https://github.com/ros-controls/roadmap/blob/master/design_drafts/hardware_access.md

**Comment by destogl** [comment]
Can we rename "Handle" to "Interface".   We are actually talking all the time about Robot-Interfaces (position, velocity, etc...)

The reason I am against the handles because it is confusing to me to access the robot through them. I am missing some clarity.

Is it me, or are there also similar opnions?

**Comment by Karsten1987** [comment]
I am in favor of renaming them to interface. That'll go along with the nomenclature we've introduced in the URDF. I'll change #203 to use `CommandInterface` and `StateInterface`. 

What do you think?
