### ISSUE TITLE
test_spawner_unspawner timouts on Jazzy builds

### ISSUE THREAD

**Issue by christophfroehlich** [ros-controls/ros2_control#1673]
https://github.com/ros-controls/ros2_control/actions/runs/10380811808/job/28741255843

`2024-08-14T03:56:58.4246421Z  9/11 Test  #9: test_spawner_unspawner ..............................***Timeout 120.03 sec`

The same test takes ~85s on rolling.

Maybe #1562 will auto-resolve this.

**Comment by saikishor** [comment]
Yes! Let's get back to it once the #1562 is merged!

**Comment by saikishor** [comment]
Fixed in https://github.com/ros-controls/ros2_control/pull/1692
