### ISSUE TITLE
Naming controller_manager causes multiple controller_manager to spawn and spawner node fail

### ISSUE THREAD

**Issue by Combinacijus** [ros-controls/ros2_control#1684]
## Description

There seems to be an issue when explicitly naming the ros2_control_node (controller_manager) node in a launch file. This issue leads to multiple instances of controller_manager being spawned, causing controller configuration to fail with an error:
```
[spawner-3] [INFO] [1723768805.754605949] [spawner_forward_position_controller]: Loaded forward_position_controller
[ros2_control_node-1] [INFO] [1723768805.756219195] [controller_manager]: Configuring controller 'forward_position_controller'
[ros2_control_node-1] [ERROR] [1723768805.756338859] [controller_manager]: 'joints' parameter was empty
[ros2_control_node-1] [WARN] [1723768805.756353356] [controller_manager]: Error occurred while doing error handling.
[ros2_control_node-1] [ERROR] [1723768805.756366772] [controller_manager]: After configuring, controller 'forward_position_controller' is in state 'unconfigured' , expected inactive.
[spawner-3] [ERROR] [1723768805.757000131] [spawner_forward_position_controller]: Failed to configure controller
```

```
ros2 node list
WARNING: Be aware that are nodes in the graph that share an exact name, this can have unintended side effects.
/controller_manager
/controller_manager
/controller_manager
```

![image](https://github.com/user-attachments/assets/8bbd7023-1e46-43e9-a9a5-b80417fb253f)

## Steps to Reproduce 

Download and checkout correct branch
```
git clone https://github.com/ros-controls/ros2_control_demos.git
git checkout humble
colcon build
```

Launch (should work without problems)
```
source install/setup.bash
ros2 launch ros2_control_demo_example_1 rrbot.launch.py
```

Edit launch file and add `name="controller_manager",`

```python
control_node = Node(
    package="controller_manager",
    executable="ros2_control_node",
    parameters=[robot_controllers],
    name="controller_manager",
    output="both",
    remappings=[
        ("~/robot_description", "/robot_description"),
    ],
```

Launch again
```
ros2 launch ros2_control_demo_example_1 rrbot.launch.py
```

Now `Failed to configure controller` error in red should be present on launch (but it's scrolled up due to verbose output)
![image](https://github.com/user-attachments/assets/4d179558-204b-4575-8d9e-151a8ca1e53a)

## Discussion

It seems strange that giving a name to any node would break it, especially when given name is exact same as default one. Moreover there's no error saying that it can't be named so it's very hard to debug as error points to other unrelated stuff.

**Comment by christophfroehlich** [comment]
The problem here is that the name is used for all controllers, which are created as node by the controller_manager (which is started from the ros2_control_node). 
It does not make sense to set the name here, but I agree that this has strange effects. Not sure if the rclcpp API supports overriding the name remapping from the our side

**Comment by vahapt** [comment]
I'm having a similar error with my custom HardwareComponentInterface class. Spawned nodes (e.g. differential_drive_controller) works as expected but the node spawned through urdf (<ros2_control> tag) prints out the following message.

```[ros2_control_node-2] [WARN] [1760260709.654928441] [rcl.logging_rosout]: Publisher already registered for node name: 'my_controller_manager'. If this is due to multiple nodes with the same name then all logs for the logger named 'test01.my_controller_manager' will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic. 	at ./src/rcl/logging_rosout.c/rcl_logging_rosout_init_publisher_for_node (227)```

Relevant code is located at:
hardware_component_interface.hpp -> init(const HardwareComponentParams&)

`hardware_component_node_ = std::make_shared<rclcpp::Node>(node_name);`

I've changed the code with the following, which solved the issue.


```
      //extract global namespace
      rclcpp::NodeOptions node_options;
      rcl_arguments_t global_args = node_options.context()->get_rcl_context()->global_arguments;
      std::string namespace_;
      char * remapped_namespace = NULL;
      rcl_ret_t ret = rcl_remap_node_namespace(
        &global_args, &global_args, "", node_options.allocator(), &remapped_namespace);
      if (ret == RCL_RET_OK && NULL != remapped_namespace)
      {
        // copy the value so we can deallocate dynamically allocated memory space
        namespace_ = remapped_namespace;

        node_options.allocator().deallocate(
          (char *)remapped_namespace, node_options.allocator().state);
      }

      //change node options after extracting namespace
      node_options.enable_logger_service(true);
      node_options.use_global_arguments(false);

      hardware_component_node_ =
        std::make_shared<rclcpp::Node>(node_name, namespace_, node_options);
      locked_executor->add_node(hardware_component_node_->get_node_base_interface());
```

---
### Suggestion:

I've also experimented with `Node::create_sub_node` function, it seems like this is much more convenient as it creates the new node under controller_manager (it is not shown as a separate node in rqt etc. but it behaves like one) and allows us to access controller_manager parameters. This is very helpful as any parameter defined for the parent controller_manager is accessible within my custom HardwareComponentInterface. Example below:

My config yaml:
```
/**/controller_manager:
  ros__parameters:
    update_rate: 50 # Hz

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    my_custom_parameter: "custom value"
```

MyCustomHardwareComponentInterface:
```
CallbackReturn MyCustomHardwareComponentInterface::on_init(const HardwareComponentInterfaceParams& params)
{
    CallbackReturn parentCallResult = SystemInterface::on_init(params);    
    if (parentCallResult != CallbackReturn::SUCCESS)
    {
        return parentCallResult;
    }

    if (get_node()->has_parameter("my_custom_parameter"))
    {
        auto param = get_node()->get_parameter("my_custom_parameter").as_string();
        RCLCPP_INFO(get_logger(), "Parameter my_custom_parameter value: %s", param.c_str());
    }

    return CallbackReturn::SUCCESS;
}
```

Changed code within hardware_component_interface:
(parent_node is the shared_ptr of ControllerManager class)

```
CallbackReturn HardwareComponentInterface::init(const hardware_interface::HardwareComponentParams & params)
...   
    std::string node_name = params.hardware_info.name;
    std::transform(
        node_name.begin(), node_name.end(), node_name.begin(),
        [](unsigned char c) { return std::tolower(c); });
      std::replace(node_name.begin(), node_name.end(), '/', '_');
      
      hardware_component_node_ = params.parent_node->create_sub_node(node_name);
      //locked_executor->add_node(hardware_component_node_->get_node_base_interface());
...
```
