### ISSUE TITLE
test_spawner_unspawner runs into timeout on source builds

### ISSUE THREAD

**Issue by christophfroehlich** [ros-controls/ros2_control#1685]
https://github.com/ros-controls/ros2_control/actions/runs/10403840300/job/28811104845
https://github.com/ros-controls/ros2_control/actions/runs/10380811808/job/28741255843

The timeout output is only visible if the raw logs are opened. 
`2024-08-14T03:56:58.4246421Z  9/11 Test  #9: test_spawner_unspawner ..............................***Timeout 120.03 sec`

Maybe the issue of both runs above is a different one. @saikishor could you take a look sometime?

**Comment by saikishor** [comment]
Sure, I'll check

**Comment by saikishor** [comment]
https://github.com/ros-controls/ros2_control/actions/runs/10429138333/job/28886186210
Another one
