### ISSUE TITLE
Add tests for parsing ros arguments to the CM

### ISSUE THREAD

**Issue by saikishor** [ros-controls/ros2_control#1714]
We need to add tests parsing different --ros-args to the CM node to be able to propagate to the controllers. This will be needed to properly add testing to the changes in #1712

**Comment by SantoshGovindaraj** [comment]
Hello @saikishor ,

I’d like to take on this issue and focus on adding tests for the function `ControllerManager::determine_controller_node_options`, where the `--ros-args` are processed and propagated to the controllers, I believe.

What I see that the function ensures:
1. Handling of `__ns` (namespace) and `__node` arguments to avoid conflicts.
2. Correct passing of parameter files through `--ros-args`.
3. Propagation of `use_sim_time` from the Controller Manager to the controllers.

So I plan to write tests covering:
- Node remapping (`__ns`, `__node`).
- Parameter file parsing.

Could you let me know if there are any additional test cases you'd like to include?

Thanks!

**Comment by saikishor** [comment]
Hello @SantoshGovindaraj!

I don't think it would be needed. I have addressed testing of this in #1713, but I forgot to link the issue. Sorry for the confusion.

**Comment by SantoshGovindaraj** [comment]
Thanks @saikishor for the update! I'll take a look at the tests in #1713. 
If I spot anything that could use more coverage, I'll let you know. Otherwise, I'll move on to another task.
