### ISSUE TITLE
Can I use like MIT control method in ros2 control?

### ISSUE THREAD

**Issue by lkx8421** [ros-controls/ros2_control#1741]
Can I use ros2 control to set the target joint positions, velocities, kp, kd and feed-forward torques of the motors?

**Comment by olivier-stasse** [comment]
You can if you hardware_interface allows it.

**Comment by lkx8421** [comment]
Could you give me some examples?

**Comment by christophfroehlich** [comment]
> Could you give me some examples?

> Can I use ros2 control to set the target joint positions, velocities, kp, kd and feed-forward torques of the motors?

As @olivier-stasse wrote, if you want to send other values than the setpoints to your power electronics then your hardware_interface has to support additional command interfaces (GPIO interfaces for example) to set the gains of your motor controller.
