### ISSUE TITLE
[Question] When to use hardware_interface::HW_IF_EFFORT  and when to use hardware_interface::HW_IF_TORQUE?

### ISSUE THREAD

**Issue by firesurfer** [ros-controls/ros2_control#1811]
I have seen in all controllers / hardware interfaces that support some kind of torque control only the hardware_interface::HW_IF_EFFORT so far and thought - okey that is what we are using for torques. I now stumbled upon hardware_interface::HW_IF_TORQUE.

I am wondering now: What is the right  type to use for an actuator that supports reading/commanding torques? 
Is there some kind of rule/standard when to use what ?

**Comment by bmagyar** [comment]
IMO if you have a torque sensor for feedback and can control torque of an
actuator, call it torque.

Effort is the more abstract term that can also mean current, acceleration,
torque or what have you. Also a non-linear combination of the above :D

**Comment by saikishor** [comment]
Yes, it is to have meaningful interfaces in your components and controllers. We have an interface remapping feature in a PR: https://github.com/ros-controls/ros2_control/pull/1667 that can help you reuse the existing controllers with new interfaces by just remapping the interface.

**Comment by firesurfer** [comment]
Thanks for the clarification !

**Comment by saikishor** [comment]
> Thanks for the clarification !

Thanks to you for bringing this up! :)
