### ISSUE TITLE
Do not repeat `TriggerType` enum in all hardware component classes

### ISSUE THREAD

**Issue by saikishor** [ros-controls/ros2_control#1958]
I think it would be a good first issue to not repeat this enum in all classes right?

_Originally posted by @bmagyar in https://github.com/ros-controls/ros2_control/pull/1567#discussion_r1891284489_

**Comment by kumar-sanjeeev** [comment]
Thanks. I have a quick question, I noticed that `TriggerType` enum is defined in two files within the `include/hardware_interface` directory i.e. `system_interface.hpp` and `actuator_interface.hpp`. Would it be okay if I will create a new file `trigger_type.hpp` in the same directory to abstract this enum from the hardware component classes?
