### ISSUE TITLE
[hardware interface] Remove rclcpp dependency

### ISSUE THREAD

**Issue by Karsten1987** [ros-controls/ros2_control#200]
Currently, rclcpp is only being used within the hardware interface to invoke the logger functionality.
I believe for this, the dependency of rclcpp is really heavy. We should consider logging through rcutils.

**Comment by bmagyar** [comment]
@mateus-amarante perhaps you may be interested in this?

**Comment by mateus-amarante** [comment]
I can get this one!

I also want to take a look at other good first issues and start playing with the lib this weekend so I can learn a bit more and maybe start contributing more actively.

Thanks.
