### ISSUE TITLE
As a ros2_control developer, I want to have CI for my PRs so I can maintain the quality and stability of my contributions

### ISSUE THREAD

**Issue by piraka9011** [ros-controls/ros2_control#21]
## Design Requirements

* Add the [`action-ros2-ci`](https://github.com/ros-tooling/action-ros2-ci) Github action to run on pull requests and create a:
  * [ ] Build and test workflow
  * [ ] Linting workflow

**Comment by gavanderhoorn** [comment]
I don't have any particular preference, but seeing as `ros-controls/ros_control` is using `industrial_ci`, I thought I'd mention the ROS 2 and Github Actions support of the refactored version.

Actions specifically mentioned here: [ros-industrial/industrial_ci/readme: Quick Start - For GitHub Actions](https://github.com/ros-industrial/industrial_ci/tree/master#for-github-actions).

**Comment by piraka9011** [comment]
@gavanderhoorn Interesting, I did not realize they had ROS2 + GH action support. 
I don't how well their ROS2 distros are supported but I don't mind using that instead for consistency.

**Comment by gavanderhoorn** [comment]
> I don't how well their ROS2 distros are supported

whose?

**Comment by piraka9011** [comment]
> whose?

Sorry, I meant the `ros-industrial/industrial_ci`.

**Comment by gavanderhoorn** [comment]
Afaik, all distros. It's docker based. But I'll wait for @ipa-mdl to comment on this.

**Comment by ipa-mdl** [comment]
> Afaik, all distros

Yep, all distros.  Even the officially unsupported ones (indigo and newer).

**Comment by gavanderhoorn** [comment]
> > Afaik, all distros
> 
> Yep, all distros. Even the officially unsupported ones (indigo and newer).

Also all ROS 2 distros, correct?

**Comment by ipa-mdl** [comment]
> Also all ROS 2 distros, correct?

Of course :sunglasses: 
All ROS distros (ROS1 and ROS2) since indigo

**Comment by bmagyar** [comment]
Since its industrial-CI is docker-based, I suppose we can expect all the
Linux coverage however what about Windows builds? Given the amount of macro
magic we may need to add to cmake, we should validate on a Windows build
too.

**Comment by bmagyar** [comment]
@piraka9011 can we please also include a source-based build of `ros2_control` in the `ros2_controllers` repo? The reason `ros_control` and `ros_controllers` have an "ros_control from source" stage in the CI is to ensure that changes to the framework were brought to the controllers too.

**Comment by bmagyar** [comment]
I think it would be very beneficial for the future to split the build and test steps on the CI as it is currently in `ros_control`. If we ever have flaky tests (which is hard to avoid unless we are willing to put a lot of time into tweaking) it makes it much quicker to re-run as the build step can be skipped.

Separate build and test steps also allow maintainers to have a better result at first glance, a failing build is more critical than a failing test.

I'm bringing this up as after the changes on #44 the gh-actions CI still fails. 

Another question: can linting be a separate stage in the CI?

**Comment by piraka9011** [comment]
> Another question: can linting be a separate stage in the CI?

Linting is currently its own workflow.

Separating build and test is non-trivial ATM since there's no mechanism to group GH actions together. `action-ros-ci` currently runs build and test to emulate the ROS2 build farm.
The MacOS issues in #44 however can be resolved and shouldn't be a blocker for not running tests. We can just have GH actions run on Ubuntu 18.04 in the meantime until that's resolved.

**Comment by bmagyar** [comment]
We've had this for a while, closing...
