### ISSUE TITLE
RobotHardware::register_joint() will invalidate existing handles

### ISSUE THREAD

**Issue by guru-florida** [ros-controls/ros2_control#212]
Calling RobotHardware::register_joint() will invalidate existing handles retrieved from get_joint_handle() since registering a new joint interface grows the underlying vector<double> of the DynamicJointState msg. Invalidated handles may produce random values or SEGV upon access. This underlying implementation detail is not explained to the API user.

**Affects**
Any use case involving pre-setup of joints, joint limits and/or PID control (i.e. control_toolbox PID)  where handles are passed off to other linked controllers.

**Workaround**
All joints should first be registered, thenceforth handles can be retrieved.  Basically split your joint setup loop into two, register joints in one while in the second loop retrieve handles and link up joint limits, PID and any other controllers.

**Solutions**
Possibly just document for now on the register_joints() method (doxygen). Possibly this will be fixed in coming PRs with Pure Components. I doubt ResourceManager will help here though so long as the handles are bound to the DynamicJointState msg and std::vector. 

I don't consider this a high priority right now but hope to start a discussion and perhaps help anyone else who may encounter this issue.

**Comment by bmagyar** [comment]
There's no `RobotHardware` anymore, this issue is obsolete
