### ISSUE TITLE
Remove `TestRobotHardware` from ros2_control_node

### ISSUE THREAD

**Issue by destogl** [ros-controls/ros2_control#217]
#216 is introducing the default ros2_control node.

Since the `ControllerManager` is currently expecting `RobotHardware` the `TestRobotHardware` class is hard-coded. 
This should be removed as soon and the interface changes and `ResourceManager` is finished. (see the comments in the code)

**Comment by Karsten1987** [comment]
I am not sure I fully understand this issue. What's the benefit of temporary hardcoding TestRobotHardware? Shouldn't the ros2_control node fetch the URDF and get the robot hardware from there?

**Comment by destogl** [comment]
When you merge #236 with ResourceManager than it is resolved. I close it anyway.
