### ISSUE TITLE
Remove parameter declaration from the ControllerManager constructor

### ISSUE THREAD

**Issue by destogl** [ros-controls/ros2_control#218]
To satisfy the CM-tests in #216, the parameters in the `ControllerManager` are declared.
This should probably not be the case (see also discussion in #168).
Find out how to set the parameters in the tests, e.g., `test_controller_manager.cpp`

**Comment by Karsten1987** [comment]
@destogl can this be closed?

**Comment by destogl** [comment]
Yes, thanks for helping with the triage!
