### ISSUE TITLE
I would be in this comment more concrete. Something like:

### ISSUE THREAD

**Issue by destogl** [ros-controls/ros2_control#221]
I would be in this comment more concrete. Something like:
```suggestion
   * The command handles ownership if relesed to the caller, i.e., ResourceManager.
```
What do you think?

__Originally posted by @destogl in https://github.com/ros-controls/ros2_control/pull/203#discussion_r514270636__

**Comment by Karsten1987** [comment]
I am closing this as I don't think there's a real need for it. @destogl feel free to re-open (and potentially rename) the issue.
