### ISSUE TITLE
SystemInterface::write() should be const

### ISSUE THREAD

**Issue by AndyZe** [ros-controls/ros2_control#227]
In system_interface.cpp:

`virtual return_type write() = 0;`

Should probably be:

`virtual return_type write() const = 0;`

since it only sends a command to the hardware

**Comment by bmagyar** [comment]
The reason for this was that we can't assume that the implementation of that function will be stateless for every component. Some components may be given APIs that are non-const or operate on stateful comms objects.

**Comment by bmagyar** [comment]
fyi @destogl @Karsten1987 if you guys have specific examples

**Comment by AndyZe** [comment]
Ok, that makes sense. May want to track the previous command, for example.
