### ISSUE TITLE
controller_manager libexec directory not found

### ISSUE THREAD

**Issue by AndyZe** [ros-controls/ros2_control#229]
When launching the `controller_manager` from a launch.py file like this:

```
    return LaunchDescription([
      Node(
        package='controller_manager',
        executable='ros2_control_node',
        parameters=[robot_description, robot_controller_file],
        output={
          'stdout': 'screen',
          'stderr': 'screen',
          },
        )
    ])
```

I get the error:

`exception=SubstitutionFailure("package 'controller_manager' found at '/home/andy/ws_ur2/install/controller_manager', but libexec directory '/home/andy/ws_ur2/install/controller_manager/lib/controller_manager' does not exist")`

Screenshot of my install directory attached.

![install_directory](https://user-images.githubusercontent.com/11284393/98574419-80acd980-227d-11eb-9b75-92412b01f535.png)

**Comment by AndyZe** [comment]
I suppose this is because the executable is not ready yet, and I just need to wait?

**Comment by destogl** [comment]
This is probably related to #172. 

Can you check it?

**Comment by bmagyar** [comment]
Is this still an issue? Any different from #172?
