### ISSUE TITLE
As a ros2_control developer, I want unit tests for my packages so I can catch regressions and failures

### ISSUE THREAD

**Issue by piraka9011** [ros-controls/ros2_control#23]
## Design Requirements

`ros2_control` currently lacks some unit tests for various packages

Specifically:

* [ ] Controller interface
  * [ ] Create a fake controller and test methods.
  * [ ] Mock the robot hardware and lifecycle node.
* [ ] Hardware interface
  * [ ] Create a fake robot and test methods.
  * [ ] Create a fake `OperationModeHandle` and test methods.
  * [ ] Create a fake `JointCommandHandle` and test methods.

**Comment by bmagyar** [comment]
It would be great if codecov could also be added to the loop with an output similar to https://github.com/fkie/catkin_lint/pull/76#issuecomment-573559415
