### ISSUE TITLE
Use constants instead of strings for standard interfaces

### ISSUE THREAD

**Issue by destogl** [ros-controls/ros2_control#250]
> looks good to me, even though I'd like to see these values then applied to other packages as well - for consistency.

I will do that, as soon as we clarify exact names.

_Originally posted by @destogl in https://github.com/ros-controls/ros2_control/pull/241#discussion_r529742582_

**Comment by destogl** [comment]
Check if there are any of the following hard-coded string:

- "position"
- "velocity"
- "acceleration"
- "effort"

Those are defined as constants [here](https://github.com/ros-controls/ros2_control/blob/master/hardware_interface/include/hardware_interface/types/hardware_interface_type_values.hpp) and should be used instead.

**Comment by mateus-amarante** [comment]
I can do that if there is no one working on it yet

**Comment by bmagyar** [comment]
Go for it!
