### ISSUE TITLE
Remove controller_name from init function in ControllerInterface

### ISSUE THREAD

**Issue by destogl** [ros-controls/ros2_control#251]
Reviewing the current controller portings in ros-control/ros2_controllers repository I realized, that this name argument is obsolete. Since controllers are `LifecycleNode`s they have access to their own name through the node name.

```suggestion
  init();
```

_Originally posted by @destogl in https://github.com/ros-controls/ros2_control/pull/236#discussion_r530619435_

Should be done with changes in #246

**Comment by bmagyar** [comment]
@destogl where do we stand on this nowadays?

**Comment by bmagyar** [comment]
@destogl @bailaC ping

**Comment by destogl** [comment]
> @destogl where do we stand on this nowadays?

I think this obsolete having `on_init` now in the controllers. Also as discussed with @bailaC this is not really implemntable and it doesn't make much sense anymore. Therefore I am closing this.
