### ISSUE TITLE
[Galactic+] Use LifecycleNode once transitions cannot be triggered by externals.

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_control#266]
Once transition triggering can be disabled through ROS2 services, we can go back to using LifecycleNode. 

LifecycleNode was replaced with Node  #261 but the code wasn't really changed, we are ready to move back as soon as possible.

**Comment by vatanaksoytezer** [comment]
I am going to start implementing this, can you assign it to me @bmagyar?

**Comment by bmagyar** [comment]
Thanks for volunteering, assigned!
