### ISSUE TITLE
Member function naming in system_interface.cpp

### ISSUE THREAD

**Issue by AndyZe** [ros-controls/ros2_control#269]
These member functions defy the Google style guidelines and the ROS C++ style guidelines. Was that intentional or should we change them?

[hardware_interface/system_interface.hpp](https://github.com/ros-controls/ros2_control/blob/master/hardware_interface/include/hardware_interface/system_interface.hpp)

For example, `export_state_interfaces()` should be `exportStateInterfaces()` per ROS1 style

Google style guide:  https://google.github.io/styleguide/cppguide.html#General_Naming_Rules
ROS1 style guide: http://wiki.ros.org/CppStyleGuide#Function_.2F_Methods

I'm happy to make a cleanup PR if needed

**Comment by AndyZe** [comment]
It looks like this is pretty widespread throughout the codebase

**Comment by gavanderhoorn** [comment]
ROS 2 C++ code style allows `snake_case`.

From [Code style and language versions - C++ - Style: Function and Method Naming](https://index.ros.org/doc/ros2/Contributing/Code-Style-Language-Versions/#function-and-method-naming):

> ![image](https://user-images.githubusercontent.com/4550046/102121976-1e7b6180-3e45-11eb-9b0b-0e72bfade2ba.png)

**Comment by AndyZe** [comment]
Cool. Maintainers, feel free to close the issue
