### ISSUE TITLE
Create Eloquent branch

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_control#27]

**Comment by bmagyar** [comment]
FYI @jordan-palacios @piraka9011 @Karsten1987

**Comment by Karsten1987** [comment]
that eloquent branch is already existing: https://github.com/ros-controls/ros2_control/tree/eloquent

**Comment by bmagyar** [comment]
Yup, I've opened this issue, pushed the branch and tagged all of yous to notify :) thanks for closing

**Comment by Karsten1987** [comment]
Just out of curiosity. Why did you create it? It’s currently on par with crystal and neither this one nor dashing has any updates.

**Comment by bmagyar** [comment]
We'll put the rosin work here that are all potentially breaking changes, didn't want to disturb those more stable releases.

**Comment by Karsten1987** [comment]
So I've restored a working version for `dashing` as well as `master`.
I am going ahead and delete the stale `eloquent` branch as all new work should be targeted against `master`.

The moment we decide to cut a release for `eloquent` we'll branch off from master.
