### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_control#278]
Stemming from https://github.com/ros-controls/ros2_control/pull/276 comments

* [ ] Capitalize messages in `controller_manager.cpp` and `resource_manager.cpp`.
* [ ] Add `'` around controller and resource names in prints, this is done already but not for all prints.

**Comment by suab321321** [comment]
@bmagyar I can do this, can you how to build this

**Comment by suab321321** [comment]
only error messages needs formatting  or `INFO, DEBUG` too?
