### ISSUE TITLE
As a robotics developer, I want to use the control_toolbox in my controllers

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_control#28]
# Design requirements
Port the classes and functionalities of `control_toolbox` over to ROS2.
Some sanitization may be required along the way: if math-specific interfaces were less tangled with ROS-specific interfaces, both the porting job and the API would benefit from it.

This is a leaf package in our dependency tree, it should already be released to ROS2 Dashing for early validation, please work against `dashing-devel`.

For now, work in the https://github.com/ros-controls/control_toolbox repo for this.

* [ ] `control_toolbox` can be compiled on ROS2 Dashing
* [ ] `control_toolbox` is released to ROS2 Dashing
* [ ] `control_toolbox` is released to ROS2 Eloquent

# References
Pending PR with partial port already done: https://github.com/ros-controls/control_toolbox/pull/81

**Comment by destogl** [comment]
It's available in foxy.
