### ISSUE TITLE
Lack of access to former release repos in ros2-gbp org

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_control#282]
The dashing release was made using the release repos in `ros2-gbp` but I couldn't simply add the new releases on top of them as I have no access there. Opted for recreating the release repos as a personal repo but ideally I'd like to use

* https://github.com/ros2-gbp/ros2_control-release and
* https://github.com/ros2-gbp/ros2_controllers-release
for making releases in the future.

Who is there to ask for admission to `ros2-gbp`? Do you guys have any pointers @Karsten1987 @chapulina @ahcorde @clalancette ?

**Comment by nuclearsandwich** [comment]
@bmagyar I've sent you an invitation to maintain both release repositories. Please let me know if you have any issues and feel free to close this issue once you have access.

**Comment by bmagyar** [comment]
Grand! Thanks @nuclearsandwich , I now have access, upcoming releases will happen using those repos :+1:
