### ISSUE TITLE
joint_limits_interface

### ISSUE THREAD

**Issue by ar0usel** [ros-controls/ros2_control#286]
I'm trying to build `gazebo_ros2_control` package, and it's depends on `joint_limits_interface` package. While building `joint_limits_interface` occurred 
```
fatal error: hardware_interface/joint_handle.hpp: No such file or directory
 #include <hardware_interface/joint_handle.hpp>
```
Can you advise version which capable with `gazebo_ros2_control`? 

My setup: Ubuntu 18.04, ros2-foxy

**Comment by ar0usel** [comment]
#https://github.com/ros-simulation/gazebo_ros2_control/issues/42

**Comment by bmagyar** [comment]
Wait for the release my friend

**Comment by bmagyar** [comment]
We haven't made up our minds about what should happen to this package, most likely it will be merged into `hardware_interface`.
