### ISSUE TITLE
problem with resource manager when validate storage

### ISSUE THREAD

**Issue by yimenghou** [ros-controls/ros2_control#298]
I guess the content in validate_storage() may not finished. There is a typo in hardware_interface/resource_manager.cpp line 377, where 'missing_command_keys' should emplace back resources instead of 'missing_state_keys'. Which may cause loading error. Besides that, hardware sensors are not validated here yet.

**Comment by bmagyar** [comment]
We aren't currently extending this section but would be happy to see if you
can produce a test case that fails or just doesn't work as intended. We
could use that as a test and have a task for someone to fix.

**Comment by bmagyar** [comment]
@Karsten1987 ?

**Comment by destogl** [comment]
> I guess the content in validate_storage() may not finished. There is a typo in hardware_interface/resource_manager.cpp line 377, where 'missing_command_keys' should emplace back resources instead of 'missing_state_keys'. Which may cause loading error.

This seems correct. We have to work on a test case for this. We need to produce an URDF to provoke this error.

> Besides that, hardware sensors are not validated here yet.

They should be [here](https://github.com/ros-controls/ros2_control/blob/40475642201e71d37ca4e622fad48ba0d6b4393f/hardware_interface/src/resource_manager.cpp#L381).

**Comment by destogl** [comment]
@Karsten1987 I work on this part for the framework this week anyway. I can than notify what is result of my tests.

**Comment by Karsten1987** [comment]
@yimenghou thanks for bringing this up. Line 377 is clearly a typo. I'll come up with a PR to fix this if you haven't started on it yet.

> Besides that, hardware sensors are not validated here yet.

What does that mean? I do believe that the validation for the sensors should be sufficient in here: https://github.com/ros-controls/ros2_control/blob/master/hardware_interface/src/resource_manager.cpp#L381-L387

**Comment by Karsten1987** [comment]
> I work on this part for the framework this week anyway. I can than notify what is result of my tests.

@destogl I consider this a clear bug and would open a separate PR for it.

**Comment by yimenghou** [comment]
Yes, hey are validated. I didn't see it right. Thanks!

> What does that mean? I do believe that the validation for the sensors should be sufficient in here: https://github.com/ros-controls/ros2_control/blob/master/hardware_interface/src/resource_manager.cpp#L381-L387
