### ISSUE TITLE
Is FakeSystem namespace confusing?

### ISSUE THREAD

**Issue by destogl** [ros-controls/ros2_control#334]
The FakeSystem has to be loaded using `fake_components/FakeSystem` name, but it is placed inside `hardware_interface` package. Is this confusing? Should we use sub-namespace?

https://github.com/ros-controls/ros2_control/blob/93b15787f1d2e16dd41d202cebff5fdbef56e19d/hardware_interface/fake_components_plugin_description.xml#L3

**Comment by AndyZe** [comment]
IMO this is not confusing.

**Comment by destogl** [comment]
Sa discissen on today's WG meeting Tihanina OK.
