### ISSUE TITLE
I propose adding `parse_bool()` function to encapsulate this logic and it could be reused by other components.

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_control#339]
I propose adding `parse_bool()` function to encapsulate this logic and it could be reused by other components.
https://github.com/ros-controls/ros2_control/blob/master/hardware_interface/include/hardware_interface/component_parser.hpp is the place to add this

_Originally posted by @bmagyar in https://github.com/ros-controls/ros2_control/pull/337#r591173829_

**Comment by destogl** [comment]
I agree, but then we have to add `type` argument in XML structure. Or how we should communicate how to parse the value?
