### ISSUE TITLE
Hardware components for simulators

### ISSUE THREAD

**Issue by olivier-stasse** [ros-controls/ros2_control#342]
Dear all, and more specifically @bmagyar @Karsten1987 @destogl,
Following the discussion in the WG, I would like to try writting hardware components for simulators.  Where such components should be located ? Is there already a repository ? 
Thanks for the directions.
Best,
Olivier.

**Comment by bmagyar** [comment]
Thanks for following up on this, I have created a repository for this: https://github.com/ros-controls/simulator_control_models

**Comment by bmagyar** [comment]
@olivier-stasse you shoudl have full access on this
