### ISSUE TITLE
Modify spawner.py and unspawner.py to use directly rclpy API

### ISSUE THREAD

**Issue by v-lopez** [ros-controls/ros2_control#344]
As discussed on https://github.com/ros-controls/ros2_control/pull/310/

The first implementation uses ros2controlcli tools to interact with the controller manager. We should modify it to use directly the services that the controller_manager provides.

It also loads a parameter file using `ros2 param load`, there's currently no rclpy API to do it (see https://github.com/ros2/rclpy/issues/671) so this could be a good opportunity to contribute to `rclpy` too.

**Comment by bmagyar** [comment]
solved by #349
