### ISSUE TITLE
use format strings for ros2controlcli

### ISSUE THREAD

**Issue by Karsten1987** [ros-controls/ros2_control#355]
rather than using `.format()`, we can use `f'...'` in Python3.6

see https://www.python.org/dev/peps/pep-0498/

**Comment by NovusEdge** [comment]
I would like to take this issue up if it's still open.

**Comment by bmagyar** [comment]
I'll put a few examples of what should be replaced and vaguely how, they may not always work, be creative ;) 

examples:
* `node.get_logger().debug('requester: making request: %r\n' % request)` ->  `node.get_logger().debug(f'requester: making request: {request}\n')`
*  `return service_caller(node, '{}/switch_controller'.format(controller_manager_name), SwitchController, request)` -> `return service_caller(node, f'{controller_manager_name}/switch_controller', SwitchController, request)`
* `node.get_logger().info('Loaded ' + param_file + ' into ' + controller_name)` -> `node.get_logger().info(f'Loaded {param_file} into {controller_name}')`

**Comment by bmagyar** [comment]
@NovusEdge I've assigned you, please tag this issue in the PR you open for reference
