### ISSUE TITLE
pep257 differences between the ros-tooling and ros-industrial CI

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_control#356]
By @Karsten1987 
> I do believe there's a fine difference in the pep257 between the ros-tooling and ros-industrial CI. The source build (ros-tooling) seems to use a version which expects a semicolon ; after a doc section, whereas the binary jobs (ros-industrial) don't.
Not sure what to do here.

https://github.com/ros-controls/ros2_control/pull/349

https://github.com/ros-controls/ros2_control/pull/349/commits/0df21e18a8f8c7e5941034344a5222c8e29cf19c

**Comment by bmagyar** [comment]
I think we should simply remove the non-tests from https://github.com/ros-controls/ros2_control/tree/master/ros2controlcli/test and let the linter workflows do their job. Those individual scripts are prune to be flaky depending on ones installed python package versions which is I believe what we are seeing with the industrial CI.

**Comment by destogl** [comment]
why not to move this into pre-commits. See here: https://www.youtube.com/watch?v=tOlnfrctpSY

**Comment by Karsten1987** [comment]
what does this mean to remove the non-tests? There aren't any inbuilt
linters for python. THese files are unfortunately copied in every package
which has python code, e.g:
https://github.com/ros2/demos/tree/master/demo_nodes_py/test

**Comment by bmagyar** [comment]
Yes and that is a problem. We are carrying dead weight. Don't want to follow a bad example. Precommit for instance is able to reliably reproduce linting work both locally editing (some) and CI validating without the flakiness of dependig and on which pytest or other tools are installed in the environment.

**Comment by Karsten1987** [comment]
sure, I am happy to have a better solution for this - as long as it's kind of transparently incorporated so that I can be able to test locally and have CI do the exact same thing as well.
