### ISSUE TITLE
ControllerManager::load_controller should return nullptr instead of throwing when a controller's class isn't found 

### ISSUE THREAD

**Issue by AugusteBourgois** [ros-controls/ros2_control#384]
At the moment, if a controller's class is not found by the loader, the controller manager will raise an exception. Why not simply returning a `nullptr` so that this can be handled as any other controller loading failure ?

I can shoot a PR with a fix as soon as you agree (see [my branch](https://github.com/ros-controls/ros2_control/compare/master...AugusteBourgois:do_not_throw_if_unknown_controller_typeown))

**Comment by destogl** [comment]
Yes, please :)

**Comment by bmagyar** [comment]
your branch looks very good, I think if we had simple unit test for this, we could incorporate it shortly

**Comment by AugusteBourgois** [comment]
The PR linking this issue has been merged. Can we close it ?
