### ISSUE TITLE
proposal of adding hardware_interface communication control flags for non real time hardware execution

### ISSUE THREAD

**Issue by ravnicas** [ros-controls/ros2_control#385]
I'd like to propose adding (maybe) a user definable flags for hardware communication.

When implementing a hardware interface to some kind of 3rd party API, for example mxAutomation, real time execution isnt guaranteed. A possible implementation would be to pass n joint configurations to the hardware, and wait until this buffer is copied.

While this happens one could set a hardware_interface::return_type::BUSY flag on the write functionality. In this case the controllers should just repeat the command, until it can be passed to the hardware.

Probably as extension to: #107

**Comment by bmagyar** [comment]
In my opinion this is a hardware-specific and the system component implementation should take care of buffering the commands in `write()` if the underlying comms are still busy. I can't see how this could become a general framework functionality without exposing a lot of vulnerability throughout the framework.
