### ISSUE TITLE
Possible error in JointCommandHandle::set_cmd(double cmd)

### ISSUE THREAD

**Issue by Mariunil** [ros-controls/ros2_control#42]
https://github.com/ros-controls/ros2_control/blob/719cb6ca5d15d77e0a765546545a5807771697a2/hardware_interface/src/joint_command_handle.cpp#L53

I believe `THROW_ON_NULLPTR` should check `cmd_` and not `cmd`.

**Comment by BrightenLee** [comment]
I'm also using ros2 controller after commenting out this line.

**Comment by Karsten1987** [comment]
This issue was addressed in https://github.com/ros-controls/ros2_control/pull/19/commits/7b9adc4f2455e624deff22527bb7e96add8b894b

I looks like the current master is not on pair with the dashing branch.
I'll address that ASAP.
