### ISSUE TITLE
Release for Galactic and Rolling

### ISSUE THREAD

**Issue by henningkayser** [ros-controls/ros2_control#421]
What's the status on releasing `ros2_control` for Galactic or Rolling?
We are planning to [release MoveIt](https://github.com/ros-planning/moveit2/issues/476) for both distros end of June and it would be great if this dependency would be available by then.

**Comment by bmagyar** [comment]
Hi @henningkayser , we talked with @vatanaksoytezer at the last WG meeting and agreed that we can go ahead with the releases. 

Unfortunately  this is currently blocked on the release of `control_msgs` in Rolling and Galactic with failures on the build farm, here's an example: https://build.ros2.org/job/Gbin_ufv8_uFv8__control_msgs__ubuntu_focal_arm64__binary/19/

I've already asked OR if they know if this is something on the buildfarm or something we can fix but I currently have no bandwidth to deep-dive into an investigation on this.

**Comment by bmagyar** [comment]
https://github.com/ros/rosdistro/pull/29786

**Comment by vatanaksoytezer** [comment]
Thanks a lot for the update @bmagyar!

**Comment by Timple** [comment]
So the `control_msgs` compile fine now on the buildfarm. Could we get a galactic release of `ros2_control`?

**Comment by vatanaksoytezer** [comment]
Thanks a ton for rolling @bmagyar: https://github.com/ros/rosdistro/pull/30070!

**Comment by cco-seasony** [comment]
Hey! Any updates on the release for Galactic?

**Comment by bmagyar** [comment]
https://github.com/ros/rosdistro/pull/30084 ros2_controllers has also been bloomed a few days ago but is being held for a rolling sync

**Comment by bmagyar** [comment]
The Galactic release is waiting for one more PR, I need to add parsing for transmissions which will result in some breaking changes - don't want to break things in the next Galactic release... A few more days and we'll have that

**Comment by tylerjw** [comment]
Any chance that PR was merged and we could get a Rolling and Galactic release?  I'm just bumping this because it has been a month and I don't see a Galactic release yet.

**Comment by hakuturu583** [comment]
Hi, I try to install ros2_control packages in ROS2 galactic.
Do you know current development/release status?

**Comment by bmagyar** [comment]
We'd like to get a couple more small ABI breaking changes merged before we release to Galactic. The last Foxy release was made a week ago and we branched for Foxy. Now `master` is for Galactic. 

If you want to help out you can here: https://github.com/ros-controls/ros2_control/issues/314

**Comment by joe28965** [comment]
Is it me or has ros2_control since been released on both Galactic and Rolling and should this issue be closed?

**Comment by bmagyar** [comment]
Oh yes of course, long since it's been released to both. Closing
