### ISSUE TITLE
As a ROS2 user I would like ros2_control controllers to follow node lifecycles

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_control#43]
This could be achieved by making the controller interface inherit from `rclcpp_lifecycle::LifecycleNode` and the rest falls into place after some adjustment in the controller implementations.

# References
* http://design.ros2.org/articles/node_lifecycle.html

**Comment by Karsten1987** [comment]
isn't that already the case?
https://github.com/ros-controls/ros2_control/blob/master/controller_interface/include/controller_interface/controller_interface.hpp#L35

**Comment by bmagyar** [comment]
It is indeed, closing...
