### ISSUE TITLE
Add clang-format file to repo

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_control#45]

**Comment by JafarAbdi** [comment]
@bmagyar Is there any style that you would prefer (for example [MoveIt clang-format](https://github.com/ros-planning/moveit/blob/master/.clang-format) .? I could create a PR to fix this issue

**Comment by bmagyar** [comment]
I think we'd be quite happy with most of that. One thing though that I remember seeing in moveit a lot is 
```
if (a)
  b();
```

while I'd prefer personally

```
if (a)
{
  b();
}
```
for more consistency. Can this be added?

**Comment by JafarAbdi** [comment]
Seems like clang-format doesn't support this, but we could use clang-tidy to do so [see](https://clang.llvm.org/extra/clang-tidy/checks/readability-braces-around-statements.html)

**Comment by bmagyar** [comment]
Could you please open a PR with this?

**Comment by Karsten1987** [comment]
for an initial start for the clang format, does this help? https://github.com/ament/ament_lint/pull/226

This at least sorts the `#includes` correctly.

**Comment by bmagyar** [comment]
opted for uncrustify to follow the crowd
