### ISSUE TITLE
Simplify dependency declarations

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_control#46]
Specifically I mean to do `build_depend + exec_depend = depend`.
Should you find anything else you could simplify/clean up, please go ahead.

**Comment by jordan-palacios** [comment]
Keep in mind that in package.xml format 2:
`<depend> = <build_depend> + <build_export_depend> + <exec_depend>`

I could not find any instances in our current packages where all three depends are being used and a `<build>` would be suitable.
