### ISSUE TITLE
Colon build failes at moveit_core

### ISSUE THREAD

**Issue by Betancourt20** [ros-controls/ros2_control#529]
Hello, I build ROS 2 from https://docs.ros.org/en/foxy/Installation/Ubuntu-Development-Setup.html with any trouble. 
Then, I'm trying to build Moveit from https://moveit.ros.org/install-moveit2/source/   foxy... But I'm stuck at the package 32 which is moveit_core and the error I get is:

Finished <<< moveit_msgs [24.1s]
Starting >>> moveit_core
--- stderr: moveit_core
/usr/bin/ld: CMakeFiles/test_distance_field.dir/test/test_distance_field.cpp.o: in function `octomap::OccupancyOcTreeBase<octomap::OcTreeNode>::insertPointCloud(octomap::ScanNode const&, double, bool, bool)':
test_distance_field.cpp:(.text._ZN7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE16insertPointCloudERKNS_8ScanNodeEdbb[_ZN7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE16insertPointCloudERKNS_8ScanNodeEdbb]+0x4a): undefined reference to `octomath::Pose6D::Pose6D(octomath::Pose6D const&)'
/usr/bin/ld: CMakeFiles/test_distance_field.dir/test/test_distance_field.cpp.o: in function `octomap::OccupancyOcTreeBase<octomap::OcTreeNode>::insertPointCloud(octomap::Pointcloud const&, octomath::Vector3 const&, octomath::Pose6D const&, double, bool, bool)':
test_distance_field.cpp:(.text._ZN7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE16insertPointCloudERKNS_10PointcloudERKN8octomath7Vector3ERKNS6_6Pose6DEdbb[_ZN7octomap19OccupancyOcTreeBaseINS_10OcTreeNodeEE16insertPointCloudERKNS_10PointcloudERKN8octomath7Vector3ERKNS6_6Pose6DEdbb]+0x51): undefined reference to `octomath::Pose6D::Pose6D(octomath::Pose6D const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [distance_field/CMakeFiles/test_distance_field.dir/build.make:229: distance_field/test_distance_field] Error 1
make[1]: *** [CMakeFiles/Makefile2:2236: distance_field/CMakeFiles/test_distance_field.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:141: all] Error 2

Failed   <<< moveit_core [7.22s, exited with code 2]

Summary: 32 packages finished [32.0s]
  1 package failed: moveit_core
  1 package had stderr output: moveit_core
  21 packages not processed

Thanks in advance for your help

**Comment by bmagyar** [comment]
Please read the error messages before you start firing bugs.

> 1 package had stderr output: moveit_core
