### ISSUE TITLE
Issues migrating the ign_ros2_control hardware_interface

### ISSUE THREAD

**Issue by Patrick-Lascombe** [ros-controls/ros2_control#557]
**Describe the bug**
I'm trying to port the package [ign_ros2_control](https://github.com/ignitionrobotics/ign_ros2_control) to galactic. I followed the steps described in [this document](http://control.ros.org/ros2_control/hardware_interface/doc/hardware_components_userdoc.html) and removed mentions of joint_state_controller. But the expected behavior of `ros2 launch ignition_ros2_control_demos cart_example_position.launch.py` is not reproduced.

**To Reproduce**
1. Clone my [galactic branch](https://github.com/wyca-robotics/ign_ros2_control/tree/galatic) of the ign_ros2_control package 
2. Put all ros2_control and ros2_controllers branches up to galactic 
3. Launch `ros2 launch ignition_ros2_control_demos cart_example_position.launch.py` and then `ros2 run ignition_ros2_control_demos example_position`

**Expected behavior**
https://github.com/wyca-robotics/ign_ros2_control/blob/galatic/img/ign_ros2_control.gif

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - ROS2 Galactic
- Ignition Edifice

**Additional context**
From the early debugging I made, the functions `read()` and `write()` from the `hardware_interface::SystemInterface` from which `IgnitionSystemInterface` inherits are never called. So I was thinking a problem of configuration/activation of the lifecycle, but I found myself stuck.

Did I miss something ? or misunderstood the foxy to galactic migration ?
Thank you for your help

**Comment by Patrick-Lascombe** [comment]
It is working with the fix and the [migration steps](http://control.ros.org/ros2_control/hardware_interface/doc/hardware_components_userdoc.html). I'll make a PR on `ign_ros2_control` from my branch

**Comment by Patrick-Lascombe** [comment]
@ahcorde Do you want me to PR right now on ahcorde/galactic/ign_ros2_control or to wait for your PR to be merged ?

**Comment by ahcorde** [comment]
Sure @Patrick-Lascombe, if you have some improvements please create a PR on top on `ahcorde/galactic/ign_ros2_control`
