### ISSUE TITLE
New release of "ros2_control" with PR 315 for next Galactic sync ?

### ISSUE THREAD

**Issue by BenjaminHug8** [ros-controls/ros2_control#572]
Hello,

Recently this [PR](https://github.com/ros-controls/ros2_control/pull/566) has solved a bug on our side.

I was wondering when the next release will be done (I saw you just made one 9 days ago) and would this release have any chance to be in the next [sync of Galactic](http://repo.ros2.org/status_page/ros_galactic_default.html?q=SYNC)?

Thank you.

**Comment by destogl** [comment]
@bmagyar can you do a new release so it comes into next sync?

@BenjaminHug8 if we do it fast it could be in.

**Comment by bmagyar** [comment]
https://github.com/ros/rosdistro/pull/31135

https://github.com/ros/rosdistro/pull/31134

**Comment by BenjaminHug8** [comment]
Perfect thank you!
