### ISSUE TITLE
Async controllers

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_control#604]
# Motivation

An asynchronous controller is a controller that for some reason cannot (or we don’t want to) perform the operations needed in an update() call.
For instance if ros control is running at 100Hz, the sum of the execution time of all controllers update() calls must be below 10ms. If a controller requires 15ms it cannot be executed synchronously without affecting the whole ros control update rate.

For more, please see https://github.com/ros-controls/roadmap/pull/48

**Comment by FranekStark** [comment]
Hi, may I ask what is the status on that?
For many hierarchical controllers, which involve an optimization problem being solved at a lower frequency, this feature would be really needed.

**Comment by saikishor** [comment]
> Hi, may I ask what is the status on that? For many hierarchical controllers, which involve an optimization problem being solved at a lower frequency, this feature would be really needed.

Hello @FranekStark!

you already have the async controllers implemented. We have a new implementation recently merged and released to rolling and jazzy, and we also have an old implementation. You can have it by simply setting the `is_async` parameter to true for the controller and remember to set the appropriate controller update rate needed for your optimization framework

**Comment by saikishor** [comment]
https://github.com/ros-controls/ros2_control/pull/1489 should solve your issue :)

**Comment by FranekStark** [comment]
@saikishor Thanks for you fast clarification! The documentation is a bit sparse on that, so I was a bit confused. :)

**Comment by christophfroehlich** [comment]
@FranekStark Contributions to control.ros.org are very welcome, what would you like to add to make that clear? And where (ros2_control, ros2_controllers, a new demo?)

**Comment by FranekStark** [comment]
@christophfroehlich I guess under ros2_control/concepts,  a document that explains how the scheduling of the controller updates works, would help a lot.
