### ISSUE TITLE
rqt_controller_manager port

### ISSUE THREAD

**Issue by wmmc88** [ros-controls/ros2_control#609]
Are there any plans to port [rqt_controller_manager](https://github.com/ros-controls/ros_control/tree/noetic-devel/rqt_controller_manager) from ros1 `ros_control`? Or is there something else that provides/replaces that functionality?

**Comment by bmagyar** [comment]
There is nothing stopping anyone from porting it but we don't have it in the works at the moment. Are you interested in doing it?

**Comment by wmmc88** [comment]
> There is nothing stopping anyone from porting it but we don't have it in the works at the moment. Are you interested in doing it?

I don't have the time to take it on at the moment, but if I get some time in the next couple of weeks, i'll throw up a pr :)

**Comment by bmagyar** [comment]
Thank you for contributing to the roadmap, added!

**Comment by bmagyar** [comment]
https://github.com/ros-controls/ros2_control/pull/813
