### ISSUE TITLE
Rename class_name to something more human-friendly

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_control#624]
`class_name` is the nomenclature of pluginlib which in this case doesn't really help people understand what this is supposed to be. We already use `plugin_name` elsewhere to refer to the same thing, let's rename this field in hardware_interface_info

_Originally posted by @destogl in https://github.com/ros-controls/ros2_control/pull/589#discussion_r785522201_

**Comment by RishiKumarRay** [comment]
HOw about plugin_lib_name?

**Comment by destogl** [comment]
We go with ‚plugin_name‘
