### ISSUE TITLE
error: expected constructor, destructor, or type conversion before ‘(’ token

### ISSUE THREAD

**Issue by A-janjan** [ros-controls/ros2_control#653]
Hello

when I build ros2_control form source , I encountered this problem:

**error:**

`ros2_control/transmission_interface/test/simple_transmission_test.cpp:162:25: error: expected constructor, destructor, or type 
 conversion before ‘(’ token
  162 | INSTANTIATE_TEST_SUITE_P(`

**Environment :**
 - OS: Ubuntu Focal Fossa (updated)
 - Version: Foxy

**Comment by bmagyar** [comment]
Please use the appropriate branch to build from source.
