### ISSUE TITLE
libhardware_interface.so build error on Ubuntu Jammy

### ISSUE THREAD

**Issue by AndyZe** [ros-controls/ros2_control#666]
Building on Rolling, which is now on Ubuntu 22 Jammy. I get this error:

```
  Starting >>> hardware_interface
  --- stderr: hardware_interface
  gmake[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libpython3.9.so', needed by 'libhardware_interface.so'.  Stop.
  gmake[1]: *** [CMakeFiles/Makefile2:192: CMakeFiles/hardware_interface.dir/all] Error 2
```

The CI log is here: 

https://github.com/ros-planning/moveit2/runs/5442497608?check_suite_focus=true

**Comment by gavanderhoorn** [comment]
Likely another case of [Preparing for Rolling sync –delayed by Python 3.10 transition–](https://discourse.ros.org/t/preparing-for-rolling-sync-delayed-by-python-3-10-transition/24521).

**Comment by rcywongaa** [comment]
Copying the comment from ruffsl here: https://answers.ros.org/question/397215/no-rule-to-make-libpython-when-using-rosidl_generate_interfaces-dependencies/?comment=397270#post-id-397270

> In the short term, you could apt install python3.9-dev to workaround this migration in the interim.
