### ISSUE TITLE
odrive_ros2_control Migration from Foxy to Galactic 

### ISSUE THREAD

**Issue by HusamZain** [ros-controls/ros2_control#676]
thank you for your work.
I'm new to this
I found an odrive_ros2_control package for Ros2 Foxy, that I want to use in my project, and I'm using galactic
I tried to do the changes as mentioned [here](https://github.com/ros-controls/ros2_control/blob/6b495ef86889cbfdc1ee22ac77efa2ff589727ee/hardware_interface/doc/hardware_components_userdoc.rst) . but I still get this error when I try to build the package
![Screenshot from 2022-03-13 18-37-24](https://user-images.githubusercontent.com/97671800/158072008-59bce08d-c034-4157-81f2-fff0ac153b77.png)
this is Foxy [package ](https://github.com/Factor-Robotics/odrive_ros2_control.git)that I'm trying to change  
and this is the [package](https://github.com/HusamZain/Odrive_ros2_control_galactic/tree/main/odrive_ros2_control/odrive_hardware_interface) after editing 

does anyone know how to solve it?

**Comment by HusamZain** [comment]
I changed all the return_type that was proposed in the documentation (configure, active ,deactive), but wasn't sure about the 'prepare_command_mode_switch', and if I do change it I got this error, sorry for the inconvenient 
![Screenshot from 2022-03-14 09-19-05](https://user-images.githubusercontent.com/97671800/158132344-190f9caf-5a5a-4d81-aaea-1caa98c11744.png)
any suggestions ?

**Comment by destogl** [comment]
Hi,

you should not change the return type of the `prepare_command_mode_switch`. If you are unsure, always check the header files of parent classes. Usually, an IDE can show you this (if configured properly).
