### ISSUE TITLE
Set up PR template

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_control#68]
Points to highlight:

* add test to new functionality
* leave resolving comments to reviewers, don't resolve them yourself
* run linters from ROS2 master

**Comment by bmagyar** [comment]
@Karsten1987 @piraka9011 please add whatever comes to your mind

**Comment by jordan-palacios** [comment]
In the same line with the linters, I'd say that all packages (old and new) must have the `ament_lint_auto` tests.

**Comment by piraka9011** [comment]
* Attach an issue if there is a related one
* Small section for description/info at the top
