### ISSUE TITLE
Ability to clear the registered handles

### ISSUE THREAD

**Issue by buschbapti** [ros-controls/ros2_control#76]
Hello,

Is there a functionality to clear the registered handles? At the moment, calling twice the init function on a hardware interface will try to register again a joint or a command resulting in an exception. The problem is that if a controller fail at configuring, the node is stuck in the not configured state as calling on_configure again will fail at the second hardware init call.

Am I missing something?
Thanks.

**Comment by destogl** [comment]
I think this is obsolete now? Can we close it?
