### ISSUE TITLE
Release branch for Galactic in rosdistro

### ISSUE THREAD

**Issue by tylerjw** [ros-controls/ros2_control#767]
![image](https://user-images.githubusercontent.com/2490389/178155870-2dfbbc32-3e2f-4632-8d04-4c436e92a221.png)

rosdistro should be updated on the next release for Galactic to point to the correct branch.

**Comment by bmagyar** [comment]
thanks for bringing our attention to this

fixed in https://github.com/ros/rosdistro/pull/33864
