### ISSUE TITLE
Transmission interface

### ISSUE THREAD

**Issue by Cryoschrome** [ros-controls/ros2_control#798]
Hi, 
I have a stepper motor with 50:1 gear ratio that I am trying to move through MoveIt2! and ros2_control. Due to which I am getting the PATH_TOLERANCE_VIOLATION.  I am guessing to tell the controller about the gear ratio I need to utilize the transmission interface. If so, could you advice me on where I can find instructions to implement it.
I am using Ubuntu 22.04 and ROS humble and actuator hardware interface

**Comment by Cryoschrome** [comment]
Can someone please provide support on how to implement transmission interface?

**Comment by destogl** [comment]
Transmission interface has to be implemented on hardware side not on the controller side. To be able to help you, you should provide many more details. From your description, I have no idea what is your issue.

**Comment by destogl** [comment]
Closing this because it is rather set up issue without activity. @Cryoschrome feel free to reopen.
