### ISSUE TITLE
Compilation on osx and windows fails

### ISSUE THREAD

**Issue by Tobias-Fischer** [ros-controls/ros2_control#803]
**Describe the bug**
After https://github.com/ros-controls/ros2_control/pull/748 which uses a Linux only method without any guards, compilation on platforms other than Linux fails.

**To Reproduce**
Try compile the project on osx or Windows, observe errors.

**Expected behavior**
Project should compile.

**Environment (please complete the following information):**
 - OS: Any other than Linux
 - Version Humble

**Comment by bmagyar** [comment]
I've changed the label as we don't really support anything other than Linux. The main reason for this is the lack of CI. You can't reliably keep a platform supported without CI backing it up.

If you'd like to fix the compilation, we are happy to review your PRs.
