### ISSUE TITLE
Add additional return value to the hardware_interface::return_type

### ISSUE THREAD

**Issue by destogl** [ros-controls/ros2_control#815]
That's exactly what I am thinking too. So we call it "SKIPPED" instead of "NOT_EXECUTED". Is this correct?

_Originally posted by @destogl in https://github.com/ros-controls/ros2_control/pull/805#discussion_r963418990_

**Comment by bailaC** [comment]
@destogl I can give it a try. Please comment if it is ok.

**Comment by destogl** [comment]
This is addressed in #1175
