### ISSUE TITLE
controller manager's update_rate not set from gazebo_ros2_control

### ISSUE THREAD

**Issue by tonynajjar** [ros-controls/ros2_control#873]
**Describe the bug**

gazebo_ros2_control uses [this constructor](https://github.com/ros-controls/ros2_control/blob/dbb626850d958f9ccde7ee861370a8c2da734818/controller_manager/src/controller_manager.cpp#L173) (see [here](https://github.com/ros-controls/gazebo_ros2_control/blob/370bc756674f5f76fbcbe41b1995b2233705e49a/gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp#L320)). This constructor does not set the update_rate from the ROS parameters, and therefore the 100 Hz default is always used.

**Comment by bmagyar** [comment]
Closing as per #874
