### ISSUE TITLE
[Question] remapping topics when spawning  controllers on existing manager

### ISSUE THREAD

**Issue by tlpss** [ros-controls/ros2_control#929]
I have a launch file that starts up the manager and spawns a number of controllers (e.g. the [launch file from the UR ROS2 drivers](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/galactic/ur_bringup/launch/ur_control.launch.py) ) and want to start an additional controller ( such as the [FZI compliance controller](https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers/blob/ros2-devel/cartesian_motion_controller/src/cartesian_motion_controller.cpp)) 

This can be done using `ros2 run controller_manager spawner -c /controller_manager -p <param-file> -t <controller_type> <name> --stopped`. However I would like to remap certain existing topics (such as the output of the wrench publisher) to the names used in this  controller, but I don't know if this is possible without modifying the launch file where the manager is started, which feels like creating a lot of code duplication.

Would appreciate it if someone could suggest a better approach!

**Comment by destogl** [comment]
This is not possible for now to do using spawners. The controllers are created under controller_manager, and I am unsure how we should provide remappings from spawners. I am not even sure if this is possible, really, since remappings are defined as arguments when a node is created.

Why don't you remap another "side"? This would be "wrench publisher" in you case.

**Comment by tlpss** [comment]
@destogl thanks for the reply. 

> Why don't you remap another “side”? This would be “wrench publisher” in your case.

Yes that would be a good alternative but I wanted to modify as little as possible to the exisiting launch files from the UR2 drivers, I find that it always creates a large amount of code duplications. 

I think the best option would actually be to have the FZI controller declare some parameters for the topic names instead of keeping them fixed, maybe I'll do a PR for that on the FZI repo.
