### ISSUE TITLE
Implement `controller_manager::checkForConflict()`

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_control#94]

**Comment by destogl** [comment]
This would be probably part of the `Actuators`, since it is only critical when controllers is doing to write simultaneously.

**Comment by bmagyar** [comment]
I disagree. The way ros_control handles this in ROS1 is that one joint
command interface can only be used by one controller at a time. This is
decided at load time. You cannot have multiple controllers trying to write
to the same joint loaded and running at once. It is not a concurrency issue
but rather a resource-management one.

**Comment by destogl** [comment]
@bmagyar I agree completely, that is what I meant, but my comment was not clear.

The point was, this is only relevant for actuators since generally sensors can be read from an arbitrary number of controlled. It would be very cool to achieve this and also important for cascade control and similar structures.

**Comment by bmagyar** [comment]
@v-lopez it seems you've covered some of this already? at least in terms of scaffoldings

**Comment by v-lopez** [comment]
The scaffoldings yes, the whole checking for conflict not though. I was under the impression that this was going to be handled with the new resource interface.

**Comment by bmagyar** [comment]
I've added this to the ros1 features and also the new components projects... I think I'll remove it from the ros1 board as it's really only relevant for components at this point

**Comment by destogl** [comment]
Although this is done for CM

#322 addressed this in ROS1 terms. There is currently only "notify" - "doSwitch" functionality. We should probably add also "trySwitch" functionality. Let's discuss it there further.

**Comment by bmagyar** [comment]
Merging this with #315
