### ISSUE TITLE
rqt_controller manager crashes on launch [humble]

### ISSUE THREAD

**Issue by MarcoMagriDev** [ros-controls/ros2_control#944]
**Describe the bug**
`rqt_controller_manager` crashes on launch

**To Reproduce**
1. Start a `controller_manager` node with some controllers loaded.
2. Start the `rqt_controller_manager`.

**Expected behavior**
No crash should occur.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version: Humble

**Additional context**
I have noticed that the issue is related to the version of the `ros2param` package currently installed. 
My version is the 0.18.5 which does the [following](https://github.com/ros2/ros2cli/blob/0.18.5/ros2param/ros2param/api/__init__.py#L235) in the `call_list_parameters()` parameter causing the crash of the function [`_get_parameter_controller_names`](https://github.com/ros-controls/ros2_control/blob/humble/rqt_controller_manager/rqt_controller_manager/controller_manager.py#L411) of the `rqt_controller_manager` with the following error:
```bash
Traceback (most recent call last):
  File "/opt/ros/humble/lib/python3.10/site-packages/rqt_controller_manager/controller_manager.py", line 160, in _on_cm_change
    self._update_controllers()
  File "/opt/ros/humble/lib/python3.10/site-packages/rqt_controller_manager/controller_manager.py", line 167, in _update_controllers
    controllers = self._list_controllers()
  File "/opt/ros/humble/lib/python3.10/site-packages/rqt_controller_manager/controller_manager.py", line 188, in _list_controllers
    for name in _get_parameter_controller_names(self._node, self._cm_name):
  File "/opt/ros/humble/lib/python3.10/site-packages/rqt_controller_manager/controller_manager.py", line 433, in _get_parameter_controller_names
    for n in parameter_names.result().result.names
AttributeError: 'list' object has no attribute 'result'
```
If I am not wrong, the first compatible version of `ros2param` with your function is the 0.20.0 which has the [following](https://github.com/ros2/ros2cli/blob/0.18.5/ros2param/ros2param/api/__init__.py#L235) version of the `call_list_parameters()` function.

I think this should be fixed on humble branch only since referring to https://index.ros.org/p/ros2param/#humble the target version for humble is the 0.18.4 (`call_list_parameters()` incompatible implementation) while regarding rolling the target version is 0.21.0 (`call_list_parameters()` compatible implementation).

**Comment by bmagyar** [comment]
hey Marco,

Since you already seem to have diagnosed the issue, would you mind submitting a pull request with a fix?

**Comment by bmagyar** [comment]
Thanks!!
