### ISSUE TITLE
Move standard names for interfaces to control_msgs

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros2_control#95]
... once stable in hardware_interface/include/hardware_interface/control_type.hpp

**Comment by destogl** [comment]
Should we gather proposals somewhere?

**Comment by bmagyar** [comment]
On this ticket?

**Comment by destogl** [comment]
OK, let's start then:

* Position
* Velocity
* Acceleration
* Effort
* Force

**Comment by bmagyar** [comment]
What do you think about adding units to these? Of course taking linear/rotary joints into account so there could be 1-2 options

**Comment by destogl** [comment]
Do you mean something like:
- Position-rad
- Position-m
- Velocity-rad/s
- velocity-m/s

**Comment by bmagyar** [comment]
Ah sorry I wasn't clear on that. I'd add some documentation to these in the messages. Not to the names/types.

**Comment by destogl** [comment]
I did something in this direction [here](https://github.com/ros-controls/ros2_control/blob/aa885a25f991b1f6e729cc46d4426342b3f31494/robot_control_components/include/robot_control_components/ros2_control_types.h#L35)

**Comment by destogl** [comment]
I think we agreed not to do this anymore since using a simple header file with constants has a smaller footprint and dependencies than messages.

@bmagyar do you agree? if so let's close this.

**Comment by bmagyar** [comment]
agreed!
