### ISSUE TITLE
Add Discussion Tab

### ISSUE THREAD

**Issue by peterdavidfagan** [ros-controls/ros2_control#950]
It would be nice to add a public GitHub discussion tab to ros_controls. I think the discussions section can be useful for tracking questions related to the use of the library. 

https://docs.github.com/en/discussions

**Comment by bmagyar** [comment]
Thanks for the suggestion. We discussed this at the last WG meeting and decided to not open a new communications channel at this point.

**Comment by peterdavidfagan** [comment]
Thanks for addressing this point @bmagyar and makes sense. I wasn't aware of the available Slack channel when opening this issue but it seems  that this is a great place for discussion.
