### ISSUE TITLE
missing header in transmission interface

### ISSUE THREAD

**Issue by GiladRobee** [ros-controls/ros2_control#960]
**Describe the bug**

**To Reproduce**
#include "transmission_interface/transmission_loader.hpp"

**Expected behavior**
successful compilation

**Screenshots**
```
/opt/ros/humble/include/transmission_interface/transmission_loader.hpp:34:27: error: ‘Transmission’ was not declared in this scope; did you mean ‘TransmissionLoader’?
   34 |   virtual std::shared_ptr<Transmission> load(
      |                           ^~~~~~~~~~~~
      |                           TransmissionLoader
/opt/ros/humble/include/transmission_interface/transmission_loader.hpp:34:39: error: template argument 1 is invalid
   34 |   virtual std::shared_ptr<Transmission> load(
```

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version Humble
- Anything that may be unusual about your environment : this happens inside and outside docker env.

**Additional context**
after adding the line:
#include "transmission_interface/transmission.hpp" to the include in:
/opt/ros/humble/include/transmission_interface/transmission_loader.hpp</br>
**the bug was fixed**

**Comment by bmagyar** [comment]
Both humble and rolling branches have received the patch for this.
