### ISSUE TITLE
Documentation ERRORS

### ISSUE THREAD

**Issue by AmmarAlbakri** [ros-controls/ros2_control#978]
I was following the documentation: https://control.ros.org/master/doc/ros2_control/hardware_interface/doc/hardware_components_userdoc.html
for migrating the ros2_control hardware interface from foxy to galactic/humble, there are some typos and missing information in the documentation, I couldn't find where to submit this issue so I thought this is the best place.

Typos:
- In step 12. **rclcpp_lifecyle** should be **rclcpp_lifecycle**
Missing steps:
- The `read();` should be changed to `read(const rclcpp::Time & time, const rclcpp::Duration & period);`
- The `write();` should be changed to `write(const rclcpp::Time & time, const rclcpp::Duration & period);`

**Comment by bmagyar** [comment]
Submit your suggestions here: https://github.com/ros-controls/ros2_control/blob/master/hardware_interface/doc/hardware_components_userdoc.rst
